name: Deploy
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          HOME: ${{ runner.tempDir }}/.ssh  # Set HOME to a temporary directory
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ecdsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > $HOME/.ssh/id_ecdsa
          chmod 600 $HOME/.ssh/id_ecdsa
          chmod 644 $HOME/.ssh/id_ecdsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> $HOME/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh padijfnh@${{ secrets.SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh

