name: Deploy
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Environment
        run: |
          echo "Running on $(hostname)"
          echo "Current user: $(whoami)"
          echo "Home directory: $HOME"
          ls -alh $HOME

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ecdsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ecdsa.pub
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ecdsa
          chmod 644 ~/.ssh/id_ecdsa.pub
          ssh-keyscan -p 21098 -H 199.188.201.205 >> ~/.ssh/known_hosts || { echo "ssh-keyscan failed"; exit 1; }

      - name: List known_hosts
        run: |
          cat ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p 21098 padijfnh@${{ secrets.SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
