name: Deploy
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          #mkdir -p $HOME/padijf/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/padijf/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > $HOME/padijf/.ssh/id_rsa.pub
          chmod 600 $HOME/padijf/.ssh/id_rsa
          chmod 644 $HOME/padijf/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> $HOME/padijf/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh syncflux@${{ secrets.SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
#deploy
